# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default

steps:
- script: echo first azure project
  displayName: 'run script line by line'
- script: gradle build
  displayName: 'build gradle application'
- script: gradle run
  displayName: 'running gradle project'
